/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihandokter;

/**
 *
 * @author arumia
 */
public class DokterFrame extends javax.swing.JFrame {

    /**
     * Creates new form DokterFrame
     */
    public DokterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtextNama = new javax.swing.JTextField();
        jtextAlamat = new javax.swing.JTextField();
        jtextJK = new javax.swing.JTextField();
        jtextUsia = new javax.swing.JTextField();
        jtextSpesialis = new javax.swing.JTextField();
        jtextWarga = new javax.swing.JTextField();
        jtextStatus = new javax.swing.JTextField();
        jtextGoldar = new javax.swing.JTextField();
        jtextWaktu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 400, 30);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 70, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setLayout(null);

        jtextNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jtextNama);
        jtextNama.setBounds(150, 30, 180, 30);
        jPanel1.add(jtextAlamat);
        jtextAlamat.setBounds(150, 70, 180, 30);
        jPanel1.add(jtextJK);
        jtextJK.setBounds(150, 150, 180, 30);
        jPanel1.add(jtextUsia);
        jtextUsia.setBounds(150, 110, 180, 30);
        jPanel1.add(jtextSpesialis);
        jtextSpesialis.setBounds(150, 350, 180, 30);
        jPanel1.add(jtextWarga);
        jtextWarga.setBounds(150, 270, 180, 30);
        jPanel1.add(jtextStatus);
        jtextStatus.setBounds(150, 230, 180, 30);
        jPanel1.add(jtextGoldar);
        jtextGoldar.setBounds(150, 190, 180, 30);
        jPanel1.add(jtextWaktu);
        jtextWaktu.setBounds(150, 310, 180, 30);

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 70, 40, 30);

        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 30, 40, 30);

        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 90, 30);

        jLabel7.setText("Usia");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 110, 40, 30);

        jLabel8.setText("Kewarganegaraan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 270, 120, 30);

        jLabel9.setText("Doktre Spesialis");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 350, 120, 30);

        jLabel10.setText("Status");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 230, 40, 30);

        jLabel11.setText("Golongan Darah");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 190, 110, 30);

        jLabel12.setText("Waktu Praktek");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 310, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 140, 350, 400);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Dokter --", "DR. Bayu Krisna", "DR. Yessy Permatasari", "DR. Arddhana Zafran", "DR. Arumia Fairuz", "DR. Aqshal Fajar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 100, 180, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton1)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 610);

        setBounds(0, 0, 410, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("DR. Bayu Krisna"))
        {
            jtextNama.setText("DR. Bayu Krisna "); 
            jtextAlamat.setText("Jl. Surabaya 16, Malang"); 
            jtextUsia.setText("20 Tahun"); 
            jtextJK.setText("Laki-Laki"); 
            jtextGoldar.setText("A"); 
            jtextStatus.setText("Belum Menikah "); 
            jtextWarga.setText("Indonesia"); 
            jtextSpesialis.setText("Dokter Umum"); 
            jtextWaktu.setText(" Pagi (07.00-15.00)"); 
       }
        else
            if(jComboBox1.getSelectedItem().equals("DR. Yessy Permatasari"))
            {
                jtextNama.setText("DR. Yessy Permatasari"); 
                jtextAlamat.setText("Jl. Veteran 3, Malang"); 
                jtextUsia.setText("20 Tahun"); 
                jtextJK.setText("Perempuan"); 
                jtextGoldar.setText("O"); 
                jtextStatus.setText("Belum Menikah"); 
                jtextWarga.setText("Indonesia"); 
                jtextSpesialis.setText("Dokter Gigi"); 
                jtextWaktu.setText(" Sore (16.00-22.00)"); 
            }
        else
            if(jComboBox1.getSelectedItem().equals("DR. Arddhana Zafran"))
            {
                jtextNama.setText("DR. Arddhana Zafran "); 
                jtextAlamat.setText("Jl. Bandung 9, Malang"); 
                jtextUsia.setText("20 Tahun"); 
                jtextJK.setText("Laki-Laki"); 
                jtextGoldar.setText("B"); 
                jtextStatus.setText("Belum Menikah"); 
                jtextWarga.setText("Indonesia"); 
                jtextSpesialis.setText("Dokter Gizi"); 
                jtextWaktu.setText(" Malam (22.00-06.00)");
            }
         else
            if(jComboBox1.getSelectedItem().equals("DR. Arumia Fairuz"))
            {
                jtextNama.setText("DR. Arumia Fairuz"); 
                jtextAlamat.setText("Perumahan Asrikaton 20, Malang"); 
                jtextUsia.setText("21 Tahun"); 
                jtextJK.setText("Perempuan"); 
                jtextGoldar.setText("A"); 
                jtextStatus.setText("Belum Menikah"); 
                jtextWarga.setText("Indonesia"); 
                jtextSpesialis.setText("Dokter Kandungan"); 
                jtextWaktu.setText(" Sore (16.00-22.00)"); 
            }
        else
            if(jComboBox1.getSelectedItem().equals("DR. Aqshal Fajar"))
            {
                jtextNama.setText("DR. Aqshal Fajar "); 
                jtextAlamat.setText("Jl. Magelang 23, Malang"); 
                jtextUsia.setText("26 Tahun"); 
                jtextJK.setText("Laki-Laki"); 
                jtextGoldar.setText("B"); 
                jtextStatus.setText("Belum Menikah"); 
                jtextWarga.setText("Indonesia"); 
                jtextSpesialis.setText("Dokter Kulit"); 
                jtextWaktu.setText(" Malam (22.00-06.00)");
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtextNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtextAlamat;
    private javax.swing.JTextField jtextGoldar;
    private javax.swing.JTextField jtextJK;
    private javax.swing.JTextField jtextNama;
    private javax.swing.JTextField jtextSpesialis;
    private javax.swing.JTextField jtextStatus;
    private javax.swing.JTextField jtextUsia;
    private javax.swing.JTextField jtextWaktu;
    private javax.swing.JTextField jtextWarga;
    // End of variables declaration//GEN-END:variables
}
